gui:
  nerdFontsVersion: "3"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --features=arctic-fox
      # command: delta --dark --paging=never --features=corvas
      # command: delta --dark --paging=never --features=collared-torogon
      # command: delta --dark --paging=never --features=calochortus-lyallii
os:
  edit: |-
    [ -z "$NVIM" ] && nvim {{filename}} || { nvim --server "$NVIM" --remote-expr "luaeval('SwitchFromLazygit()')" && nvim --server "$NVIM" --remote {{filename}}; }
  editAtLine: |-
    [ -z "$NVIM" ] && nvim +{{line}} {{filename}} || { nvim --server "$NVIM" --remote-expr "luaeval('SwitchFromLazygit()')" && nvim --server "$NVIM" --remote +{{line}} {{filename}}; }
promptToReturnFromSubprocess: false
