require "user.options"
require "user.keymaps"
require "user.autocmds"

local register = require("user.plugin_registry").register

register "user.colorschemes.onenord"

register "user.autopairs"
register "user.luasnip"
register "user.alpha"
register "user.breadcrumbs"
register "user.cmp"
register "user.comment"
register "user.conform"
register "user.dap"
register "user.devicons"
register "user.flash"
register "user.fyler"
register "user.gitsigns"
register "user.git-conflict"
register "user.go"
register "user.hlchunk"
register "user.illuminate"
register "user.lint"
register "user.lsp-config"
register "user.lualine"
register "user.mason"
register "user.mini-ai"
-- register "user.mini-pairs"
register "user.mini-surround"
register "user.navic"
register "user.neotest"
register "user.schemastore"
register "user.telescope"
register "user.toggleterm"
register "user.todo-comments"
register "user.treesitter"
register "user.trouble"
register "user.ts-autotag"
register "user.whichkey"

register "user.extras.bqf"
register "user.extras.colorizer"
register "user.extras.copilot"
register "user.extras.dressing"
register "user.extras.eyeliner"
register "user.extras.gitlinker"
register "user.extras.hlargs"
register "user.extras.neoscroll"
register "user.extras.noice"
register "user.extras.nvim-dbee"
register "user.extras.nvim-spider"
register "user.extras.obsidian"
register "user.extras.octo"
register "user.extras.quicker"
register "user.extras.registers"
register "user.extras.remote-nvim"
register "user.extras.render-markdown"
register "user.extras.sidekick"
register "user.extras.smart-splits"
register "user.extras.treesj"
register "user.extras.ufo"
register "user.extras.wezterm-types"

require "user.lazy"

require "user.lsp"
