require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.colorschemes.onenord"

spec "user.luasnip"
spec "user.alpha"
spec "user.autopairs"
spec "user.barbar"
spec "user.breadcrumbs"
spec "user.cmp"
spec "user.comment"
spec "user.dap"
spec "user.devicons"
spec "user.flash"
spec "user.fyler"
spec "user.conform"
spec "user.gitsigns"
spec "user.git-conflict"
-- spec "user.go" -- treesitter main移行でエラーになるので対応まち
spec "user.harpoon"
spec "user.hlchunk"
spec "user.illuminate"
spec "user.lint"
spec "user.lsp-signature"
spec "user.lsp-config"
spec "user.mason"
spec "user.lualine"
spec "user.mini-ai"
spec "user.mini-surround"
spec "user.navic"
spec "user.neotest"
-- spec "user.nvimtree.nvimtree"
spec "user.schemastore"
spec "user.telescope"
spec "user.toggleterm"
spec "user.todo-comments"
spec "user.treesitter"
spec "user.trouble"
spec "user.ts-autotag"
spec "user.whichkey"

spec "user.extras.bqf"
-- spec "user.extras.claudecode"
spec "user.extras.colorizer"
spec "user.extras.copilot"
-- spec "user.extras.codex"
spec "user.extras.dressing"
spec "user.extras.eyeliner"
spec "user.extras.fidget"
spec "user.extras.gitlinker"
spec "user.extras.hlargs"
spec "user.extras.neoscroll"
spec "user.extras.nvim-dbee"
spec "user.extras.nvim-spider"
spec "user.extras.obsidian"
spec "user.extras.octo"
spec "user.extras.quicker"
spec "user.extras.registers"
spec "user.extras.remote-nvim"
spec "user.extras.render-markdown"
spec "user.extras.sidekick"
spec "user.extras.smart-splits"
spec "user.extras.treesj"
spec "user.extras.ufo"

require "user.lazy"

require "user.lsp"
