require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.none-ls"
spec "user.whichkey"
spec "user.telescope"
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.harpoon"
spec "user.illuminate"
spec "user.autopairs"
spec "user.neotest"
spec "user.gitsigns"
spec "user.project"
spec "user.indent-brankline"
spec "user.toggleterm"

-- spec "user.extras.copilot"
spec "user.extras.tabby"
spec "user.extras.neoscroll"
spec "user.extras.ufo"
spec "user.extras.eyeliner"
spec "user.extras.neotab"
spec "user.extras.gitlinker"
spec "user.extras.bqf"
spec "user.extras.colorizer"
-- spec "user.extras.modicator"

require "user.lazy"
