# XDG
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state

# history
# 履歴ファイルの保存先
export HISTFILE=${ZDOTDIR}/.zsh_history
# メモリに保存される履歴の件数
export HISTSIZE=100000
# 履歴ファイルに保存される履歴の件数
export SAVEHIST=100000
export HISTFILESIZE=100000

# bat
export BAT_THEME="Nord"

# EDITORにnvimを設定するとkeybindもvimになる
# 意図してない場合は`bindkey -e`でemacsに戻す必要あり
# https://unix.stackexchange.com/questions/197839/why-does-exporting-vim-as-editor-in-zsh-disable-keyboard-shortcuts
export EDITOR="nvim"
export VISUAL="nvim"
